server:
  port: 8081

#mongodb
spring:
    application:
      name: registration-service
    data:
        mongodb:
            host : localhost
            port : 27017
            database : chargie
    
    config:
      import: optional:configserver:http://localhost:8888
    cloud:
        config:
            uri : file:///G:/microservices/git-localconfig-repo
            profile: dev
    profiles:
      active: dev

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka